### ISSUE TITLE
I have another question with audioInputStream.skip()

### ISSUE THREAD

**Issue by Kokecena** [hendriks73/ffsampledsp#13]
Yeah it's me again, sorry 😥, I will try to put you in context, I am rewriting an old abandoned project and everything using your library, everything so far works perfectly well, the problem comes when I want to jump to some second of the song, there is a ```seek()``` listener method in charge of executing when you do click to some position of the JSlider, internally it passes the parameter to the method of my player in this case ```seek(long byte)```  I pass the following formula as a parameter

```Math.round(<Total size in bytes of the audioinputstream> * (double) <current selected second> / <duration of the song in milliseconds>)```

and inside the method, the person in charge of skipping the song is the ```audioInputStream.skip (bytes);``` this same formula and code is exactly the same as the one in the project.

My observations have been at least those that I have tried both in mp3 and in ogg, it happens that they remain as 1 or 1:45 minutes from the total of the song

In Flac format something else happens, and that is that it ends 1 to 2 minutes before, I have not tried other formats.
So I don't know what I'm doing wrong if it's me and I have to program this part in another way in which I can't think of any, or another is that it is somehow affected by your library.

In both cases, as I mentioned, it only happens when I want to jump to some part of the song.

I am not using a ```Clip``` to play the file I use a ```SourceDataLine```, hope my problem is understood

**Comment by Kokecena** [comment]
https://user-images.githubusercontent.com/75457600/145736365-a05e99d1-f847-4862-840b-7ac902136e37.mp4

Everything works perfect when it is allowed to reproduce, but when I jump to some second this happens

**Comment by Kokecena** [comment]
https://user-images.githubusercontent.com/75457600/145736477-e78003b6-4fa4-48a2-a58b-55846ac73da4.mp4

Everything works perfect when it is allowed to reproduce, but when I jump to some second this happens

**Comment by hendriks73** [comment]
Sorry for the late reply. I have an idea where this might be coming from (a side-effect of the earlier "fix") and plan on fixing it, but currently don't have the time. Sorry.

**Comment by Kokecena** [comment]
Hi, Merry Christmas haha, don't worry, I actually solved it, relatively, I divided the total duration of the song by some magic number that would fit relatively well with most songs and well, it works more or less, but well it's functional haha
![Magic numbers](https://user-images.githubusercontent.com/75457600/147745879-7f1dfcc2-bcdd-4303-8e1b-3f76a5f58810.PNG)


https://user-images.githubusercontent.com/75457600/147746176-02523223-ff0c-478a-ab1b-f7a51a51d09b.mp4

In the longest songs it has a margin of error of 1s to 3s and in others of 1s or less, but I repeat it is functional for me, do not worry, happy new years holidays 😄😃

**Comment by Kokecena** [comment]
Hello, sorry for the delay, I just updated to 0.9.45 and tried to do it again with the formula but the same thing still happens, or is there any other way to skip to the second of a song without using the skip method?

**Comment by hendriks73** [comment]
That leaves me puzzled. Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Kokecena** [comment]
Excuse me for being confused, I meant to use the skip method of the AudioInputStream class to skip a second of a song but it's fixed now, everything works fine, thanks for the fixes you made :a, I have a question and I'll leave it at Peace 😥, what formats does it support? Currently I only put the FLAC, AAC, M4A, OGG and MP3 formats on my player, but I really don't know the range of audio formats your library has, and the website doesn't make it very clear to me what they are, and sorry for the inconvenience

**Comment by hendriks73** [comment]
FFSampledSP is built on https://www.tagtraum.com/ffmpeg/ and supports pretty much everything FFmpeg supports, minus the formats disabled in the configuration described at https://www.tagtraum.com/ffmpeg/#Configuration So there is plenty more formats, but not a concrete list.

**Comment by Kokecena** [comment]
Understood, I really appreciate the bug fixes, thanks to your library now I have a beautiful player with support for various formats. 

![image](https://user-images.githubusercontent.com/75457600/150454435-872f1832-e79e-4093-8002-6163102be770.png)

I will recommend this library because I feel that it is not well known, when I was looking for something to play mp3 they always throw me libraries like JLayer 😄

**Comment by hendriks73** [comment]
Very nice! Is your player available somewhere?

> I will recommend this library

Thank you. Please do! :-)

This may not be of any value to you, because you show amplitudes (or RMS or the like), but check out https://github.com/hendriks73/audioplayer4j It's a (non-visual) audio player with a nice and simple API.

**Comment by Kokecena** [comment]
Well, I really don't know, it's just a project to say goodbye to the fun of Java and start with the boring and highly requested SpringBoot or Spring, those famous frameworks... and why current players have so many things that I don't even use, so I started mine, anyway I will upload it to GitHub and I will upload a video of its use, there I will reference all the libraries that I have been occupying, and in the player an "About..." section where I will refer to the authors of the libraries that I occupy and their GitHub references

> This may not be of any value to you, because you show amplitudes (or RMS or the like), but check out https://github.com/hendriks73/audioplayer4j It's a (non-visual) audio player with a nice and simple API.

Wow it's so simple that if I had found it before, I don't think I would have put the visualizations, it was a headache to see how to implement them, Seeing the API code, it supports change of output audio device at runtime, right? That's great, not long ago I tried to implement it in my player, but I had to restart the program and I was looking for something in real time, but I gave up. and I settle for just plugging in my headphones
