### ISSUE TITLE
Add binaries for ARM

### ISSUE THREAD

**Issue by MMarco94** [hendriks73/ffsampledsp#17]
Could you please add binaries so this library can work on ARM on Linux?

Thanks!

**Comment by hendriks73** [comment]
What's the actual target platform?
Are you thinking of a specific Linux for ARM OS? Like Android?

**Comment by MMarco94** [comment]
> What's the actual target platform?

`linux-arm64` and ideally `linux-arm32`.

I don't have a specific device in mind, but there are plenty of ARM devices running Linux: Chromebooks, M1 macs with Ashai linux, tablets and some laptops.

**Comment by hendriks73** [comment]
v0.9.52 *should* now work on linux-arm64. However, since GitHub does not offer any arm64 runners, it's difficult to test this in the CI/CD pipeline.

If you have access to a Linux arm64 system, please test it manually and report back. Here's the maven dependency you should use for that:

```
<dependency>
    <groupId>com.tagtraum</groupId>
    <artifactId>ffsampledsp-complete</artifactId>
    <version>0.9.52</version>
</dependency>
```

I do not plan to add arm32.

**Comment by MMarco94** [comment]
Thanks!
I don't have access to an ARM linux host, however I've asked a friend. I'll let you know

**Comment by hendriks73** [comment]
Any news on this one?

**Comment by MMarco94** [comment]
No sorry, I went on holidays and didn't follow up. I've sent him a message :)

**Comment by hendriks73** [comment]
Any response?

I'd like to close this issue with a confirmation that things work, but will close it anyway in August.

**Comment by hendriks73** [comment]
I'm closing this issue, as the implementation work has been done and there is little reason to believe that it does not work. That said, obviously, without a proper test we cannot know. If you find that it does not work on 64 bit ARM Linux, please create a new issue.

Thanks.
