### ISSUE TITLE
Failed to load native library 'ffsampledsp'. Please check your library path. FFSampledSP will be dysfunctional.

### ISSUE THREAD

**Issue by xumf** [hendriks73/ffsampledsp#21]
environment as the below following is shown:
maven: ffsampledsp-complete:0.9.52
jdk: 17

**Comment by hendriks73** [comment]
Which OS? Stacktrace?

**Comment by xumf** [comment]
linux arch=x86_64,
There aren't any stacktrace. 
I am sorry,can't give you any stacktrace.I will close the issue.
