### ISSUE TITLE
Can I do silence trimming with ffsampledsp?

### ISSUE THREAD

**Issue by ovninosa** [hendriks73/ffsampledsp#4]
Hello,

I want to remove silence from beginning and end of a wav just with a threshold.

Can I do this with this library?

THanks
Jave

**Comment by hendriks73** [comment]
You don't need this library for that. Just use the standard APIs.

**Comment by javenosa** [comment]
@hendriks73 I googled for about 2 hours and I cannot find any sample to do it with the standard API.

Do you have any good resource to use as example?

Thanks
Jave

**Comment by hendriks73** [comment]
You need to decode the WAV to PCM. Then take chunks of samples and average their absolute values. Those averages can be seen as approximations of loudness, which can help you to detect relative "silence".

To get started with Java and audio, you need to learn the `javax.sound.sampled` API. For starting points, see https://stackoverflow.com/tags/javasound/info
